### ISSUE TITLE
Not able to select group for room restriction

### ISSUE THREAD

**Issue by garblixa** [sualko/cloud_bbb#65] opened 2020-08-17 12:34 UTC
**Describe the bug**
Want to restrict the room access only for a single group. We have groups (classes) with only one number e.g. "3". Groups with only one number are not available in the search field. Groups with more than one number appear.

**To Reproduce**
1. Create a room
2. Click on Edit
3. Select "Access" - "restricted internally"
4. Type in "3" (an existing group) - the group does not appear.

**Expected behavior**
Any group available in nextcloud should be available

**System (please complete the following information):**
 - Any browser
 - App version 0.5.1
 - Nextcloud version 19.0.1
 - Did you enter your BBB API url and secret? yes

Kind regards
Klaus

**Comment by sualko** [comment] 2020-08-25 10:49
Does the room occur in the normal file share dialog? Because we use the same endpoint.

**Comment by garblixa** [comment] 2020-08-26 08:09
I don't know what you mean with your questions if the **room** does occur in the normal file share dialog. If you mean the **group** then, yes, it is available in the normal file share dialog.

**Comment by joergmschulz** [comment] 2020-08-26 09:58
if I remember correctly the standard name/group search only starts when the 3rd character has been entered. Your group names should be longer.

**Comment by garblixa** [comment] 2020-08-26 10:36
Sorry, this is not correct. Many of my LDAP Groups (school classes) only contain 1 character:
Class: 1 2 3 4. And all of them are available within all Nextcloud apps. This bug should be fixed in cloud_bbb

**Comment by sualko** [comment] 2020-08-26 11:16
The issue is that the api returns suggestions and exact matches separately. We use only suggestions for the drop down, therefore one letter groups are currently not showing up. Will be fixed in the next release.

**Closed** 2020-08-26 13:55 UTC
Labels: bug

**Comment by garblixa** [comment] 2020-08-27 13:34
Thank you for the fix!
