### ISSUE TITLE
UX-Nav: Customize header text in settings

### ISSUE THREAD

**Issue by CSchmidtDD** [sualko/cloud_bbb#133] opened 2021-03-18 10:36 UTC
**Is your feature request related to a problem? Please describe.**
1. When installing the Add-On via Nextcloud-Store, the name in the navigation bar (after enabling it) is 'BigBlueButton' which interferes with other navigation items.
2. The settings page for the Add-On does not offer the functionality to change the name used there. More interestingly, the change is already possible via CLI, but not via the settings page.
 
**Describe the solution you'd like**
1. Per default, the first name to set the UX-Header to should be 'BBB' instead of the longer 'BigBlueButton', so it will not interfere with other navigation elements.
2. There should be an additional setting via textbox ans save-button to change the display name in the UX.

**Describe alternatives you've considered**
These changes are mainly UX-focused and therefore not absolutely nessecary, but complete the already implemented featureset and give some more customization to the table.

**Additional context**

**_How it looks right now:_** 
![bigbluebutton1](https://user-images.githubusercontent.com/10221959/111607047-2cd87100-87d8-11eb-8fea-f47519d0dac4.png)

**_How it should look:_**
![bigbluebutton](https://user-images.githubusercontent.com/10221959/111607089-36fa6f80-87d8-11eb-9aea-e0888af418b0.png)

![settings](https://user-images.githubusercontent.com/10221959/111612767-1a613600-87de-11eb-83bb-e1851aab8f59.PNG)

INFO: I have already created the nessecary changes and will reference the Pull Request accordingly to the Feature-Request.

Best Regards

PS: Greetings from @T-Systems-MMS

**Comment by sualko** [comment] 2021-04-12 15:20
This is a duplicate of #124.

**Closed by sualko** 2021-04-12 15:20 UTC
