### ISSUE TITLE
Nextcloud room list only showing rooms created by that user

### ISSUE THREAD

**Issue by Aranad** [sualko/cloud_bbb#163] opened 2021-07-05 16:36 UTC
We have just enabled the BigBlueButton extension to integrate our BBB server with our Nextcloud. It works like a charm! Except for one big problem: the room list in the Nextcloud only shows for the creator, none of the other NC users see the rooms even if they're explicitly added to the permitted users list.

The behaviour we expected was that when we create a room, that is for internal use (i.e. usable by all our nextcloud users), they should all see that room in the list of BBB rooms within the nextcloud BBB rooms page.

 - The problem applies to all browsers
 - App version 1.4.1
 - Nextcloud version 20.0.10
 - BigBlueButton version 2.8.7
 - Is your BigBlueButton instance working with Greenlight? yes
 - Did you enter your BBB API url and secret? yes

There are no errors, the room works perfectly when the creator clicks on it, or if we use "internal + waiting room", then it also works perfectly for the people using the invite link.

**Comment by Aranad** [comment] 2021-07-05 19:26
I've noticed that if I add different users to the room moderators list, then they're able to see the room. But when I select "every participant is a moderator", still only the ones that were specifically added to the moderator list can see it.

**Comment by sualko** [comment] 2021-07-05 19:37
The list contains only rooms which you have admin access to. This is intended. Use file links to share normal rooms. This has the advantage, that you can put all material + room into one folder which is synchronized across all your devices.

Btw duplicate of #146.

**Closed by sualko** 2021-07-05 19:37 UTC
