### ISSUE TITLE
Install on Nextcloud 22.0.0 fails

### ISSUE THREAD

**Issue by pasith3e** [sualko/cloud_bbb#165] opened 2021-07-08 09:38 UTC
**Describe the bug**

Install on Version 22.0.0 of Nextcloud fails with Error message:
Column "oc_bbb_rooms"."record" is type Bool and also NotNull, so it can not store "false".
 

**To Reproduce**
1. Download BigBlueButton Integration in NC Appstore
2. Activation fails on Webinterface with message: "Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden."
3. Activation via _php occ app:enable bbb_ fails with message: "Column "oc_bbb_rooms"."record" is type Bool and also NotNull, so it can not store "false"."

**Expected behavior**
The App should be installed successfully. 

**System:**
 - Browser with version Firefox 89.0.2
 - App version  1.4.2
 - Nextcloud version 21.0.0

**Nextcloud log:**
Only on app Activation in Browser:
{"reqId":"********","level":3,"time":"2021-07-08T09:27:49+00:00","remoteAddr":"******","user":"*****","app":"settings","method":"POST","url":"/index.php/settings/apps/enable","message":"could not enable apps","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0","version":"22.0.0.11","exception":{"Exception":"InvalidArgumentException","Message":"Column \"oc_bbb_rooms\".\"record\" is type Bool and also NotNull, so it can not store \"false\".","Code":0,"Trace":[{"file":"******/lib/private/DB/MigrationService.php","line":461,"function":"ensureOracleConstraints","class":"OC\\DB\\MigrationService","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"},{"__class__":"Doctrine\\DBAL\\Schema\\Schema"},3]},{"file":"****/lib/private/DB/MigrationService.php","line":417,"function":"migrateSchemaOnly","class":"OC\\DB\\MigrationService","type":"->","args":["latest"]},{"file":"*****/lib/private/Installer.php","line":154,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->","args":["latest",true]},{"file":"******/apps/settings/lib/Controller/AppSettingsController.php","line":447,"function":"installApp","class":"OC\\Installer","type":"->","args":["bbb"]},{"file":"*****/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":[["bbb"],[]]},{"file":"*****lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"*****/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"*****/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"*****/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"****/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"****/lib/private/DB/MigrationService.php","Line":595,"CustomMessage":"could not enable apps"}}

**Comment by sualko** [comment] 2021-07-08 10:02
duplicate of #164

**Closed by sualko** 2021-07-08 10:02 UTC
