### ISSUE TITLE
Scrolling up and down is not possible in BigBlueButton App in combine with Nextcloud version 25.0.x if many Videoconferenzrooms are created

### ISSUE THREAD

**Issue by EGVuser** [sualko/cloud_bbb#245] opened 2023-04-13 12:27 UTC
**Describe the bug**
I upgraded my Nextcloud from version 24. to 25.0.3 to 25.0.5
In version 24 the BBB app worked perfectly with round about 30 video conference room.
Since updating Nextcloud Version 25 Scrolling up and down is not possible in BBB App

**To Reproduce**

    open BBB App in Nextcloud
    Create many Conference rooms About 30 ore more
    No scrollbar is shown and srolling is not possible

**Expected behavior**
I expect to scroll up and down to navigate to select a conference room

**Screenshots**
![image](https://user-images.githubusercontent.com/62250151/231750243-50140b94-d18c-44d0-b3c1-614334dad7e2.png)

**System (please complete the following information):**
 - Browser with version [e.g. chrome version 108 Firefox 110, ]
 - App version [e.g. 2.4.0]
 - Nextcloud version [e.g. 25.0.5]
 - BigBlueButton version [e.g. 2.2.9]
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes
 - Are you using a load balancer, like Scalelite? no

**Nextcloud log:**

{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 174","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 205","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Polls\\Cron\\NotificationCron job with ID 205","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Polls\\Cron\\NotificationCron job with ID 205 in 0 seconds","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 227","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 317","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 319","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\UserStatus\\BackgroundJob\\ClearOldStatusesBackgroundJob job with ID 319","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\UserStatus\\BackgroundJob\\ClearOldStatusesBackgroundJob job with ID 319 in 0 seconds","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 332","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 333","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Talk\\BackgroundJob\\CheckMatterbridges job with ID 333","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Talk\\BackgroundJob\\CheckMatterbridges job with ID 333 in 1 seconds","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 340","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 349","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 406","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 411","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 423","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 427","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Circles\\Cron\\Maintenance job with ID 427","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"","method":"","url":"--","message":"[debug] running maintenance (2)","userAgent":"--","version":"24.0.11.1","data":{"app":""}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"","method":"","url":"--","message":"[debug] running maintenance (1)","userAgent":"--","version":"24.0.11.1","data":{"app":""}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Circles\\Cron\\Maintenance job with ID 427 in 0 seconds","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 430","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 433","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\FilesLock\\Cron\\Unlock job with ID 433","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":1,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"files_lock","method":"","url":"--","message":"[notice] ConfigService::LOCK_TIMEOUT is not numerical, using default","userAgent":"--","version":"24.0.11.1","exception":{"Exception":"OC\\HintException","Message":"[notice] ConfigService::LOCK_TIMEOUT is not numerical, using default","Code":0,"Trace":[{"file":"/srv/www/htdocs/owncloud/apps/files_lock/lib/Tools/Traits/TLogger.php","line":158,"function":"log","class":"OCA\\FilesLock\\Service\\LockService","type":"->"},{"file":"/srv/www/htdocs/owncloud/apps/files_lock/lib/Service/LockService.php","line":287,"function":"notice","class":"OCA\\FilesLock\\Service\\LockService","type":"->"},{"file":"/srv/www/htdocs/owncloud/apps/files_lock/lib/Cron/Unlock.php","line":54,"function":"getDeprecatedLocks","class":"OCA\\FilesLock\\Service\\LockService","type":"->"},{"file":"/srv/www/htdocs/owncloud/apps/files_lock/lib/Cron/Unlock.php","line":50,"function":"manageTimeoutLock","class":"OCA\\FilesLock\\Cron\\Unlock","type":"->"},{"file":"/srv/www/htdocs/owncloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\FilesLock\\Cron\\Unlock","type":"->"},{"file":"/srv/www/htdocs/owncloud/lib/public/BackgroundJob/TimedJob.php","line":95,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/srv/www/htdocs/owncloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/srv/www/htdocs/owncloud/apps/files_lock/lib/Tools/Traits/TLogger.php","Line":181,"Hint":"{\"current\":0}","message":"[notice] ConfigService::LOCK_TIMEOUT is not numerical, using default","exception":{},"CustomMessage":"[notice] ConfigService::LOCK_TIMEOUT is not numerical, using default"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\FilesLock\\Cron\\Unlock job with ID 433 in 0 seconds","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 434","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Polls\\Cron\\AutoReminderCron job with ID 434","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Polls\\Cron\\AutoReminderCron job with ID 434 in 0 seconds","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 443","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 444","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Notifications\\BackgroundJob\\SendNotificationMails job with ID 444","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Notifications\\BackgroundJob\\SendNotificationMails job with ID 444 in 0 seconds","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 463","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 6","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}
{"reqId":"IqQsr9nM1VlM0ImvE0HA","level":0,"time":"2023-04-13T11:00:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 477","userAgent":"--","version":"24.0.11.1","data":{"app":"cron"}}

```

**Javascript log:**
<!-- Are there any errors or entries in your javascript console related to this app? You can open the console with CTRL+SHIFT+I -->

```

```

**Additional context**
Add any other context about the problem here.

**Comment by battosai30** [comment] 2023-04-21 14:47
https://github.com/sualko/cloud_bbb/issues/227

**Comment by sualko** [comment] 2023-07-27 09:10
duplicate of #227, but nice bug report :+1:

**Closed by sualko** 2023-07-27 09:10 UTC
