### ISSUE TITLE
Cannot start conference from files menu

### ISSUE THREAD

**Issue by hokascha** [sualko/cloud_bbb#46] opened 2020-06-05 09:47 UTC
**Describe the bug**
When trying to start a conference from the files context dot-menu the site says it could not complete the request.

**To Reproduce**
1. Go to 'Files'
2. Click on '...' beside a pdf file
3. choose your conference room

**Expected behavior**
The conference should start using the chosen file.

**System (please complete the following information):**
 - Chrome
 - App version 0.3.2
 - Nextcloud version 18.0.5
 - BigBlueButton version 2.2.0-5
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:**

```

Error | index | Exception: String could not be parsed as XML |   | vor 6 Minuten
-- | -- | -- | -- | --
Error | PHP | SimpleXMLElement::__construct(): ^ at /var/www/nextcloud/apps/bbb/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php#500 |   | vor 6 Minuten
Error | PHP | SimpleXMLElement::__construct(): &lt;!doctype html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;&lt;title&gt;HTTP Status 500 – Internal Server at /var/www/nextcloud/apps/bbb/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php#500 |   | vor 6 Minuten
Error | PHP | SimpleXMLElement::__construct(): Entity: line 1: parser error : Extra content at the end of the document at /var/www/nextcloud/apps/bbb/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php#500 |   | vor 6 Minuten
Error | PHP | SimpleXMLElement::__construct(): ^ at /var/www/nextcloud/apps/bbb/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php#500 |   | vor 6 Minuten
Error | PHP | SimpleXMLElement::__construct(): &lt;!doctype html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;&lt;title&gt;HTTP Status 500 – Internal Server at /var/www/nextcloud/apps/bbb/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php#500 |   | vor 6 Minuten
Error | PHP | SimpleXMLElement::__construct(): Entity: line 1: parser error : StartTag: invalid element name at /var/www/nextcloud/apps/bbb/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php#500


```

**Comment by sualko** [comment] 2020-06-10 07:19
Does it work from the room overview page? Did you get a positive response while saving the BBB url and secret?

It looks like your api url is wrong.

**Comment by hokascha** [comment] 2020-06-10 08:46
Yes, it works from the rooms overview page.

**Comment by sualko** [comment] 2020-06-10 09:51
It's using the same logic on both pages and I can't reproduce it, so I don't know how I can debug this. It would be nice if you could try to get more information.

**Comment by hokascha** [comment] 2020-06-10 10:02
The Nextcloud logs indicate a HTTP 500 error while parsing a xml file. Could you give me some information on where that file is requested from? The BBB server? Maybe I can find error logs there.

**Comment by sualko** [comment] 2020-06-10 10:12
It looks like your BBB server response with a error 500, so you should find there more information. Maybe he can't request the presentation, because of some certificate issue or something similar. Maybe also the presentation share is failing and therefore the BBB server can't load your presentation and fails therefore.

**Comment by sualko** [comment] 2020-06-10 10:15
> So maybe there's some error while file uploading which is what I suppose POST is used for here.

We don't upload a file. We create a share url which is added to the request body. Your BBB server than tries to download the file. I guess it fails at this point. So please make sure your Nextcloud server is configured probably and reachable from the BBB server. I guess there is more information somewhere in the `/var/log/bigbluebutton` dir.

**Comment by sualko** [comment] 2020-06-10 10:18
> Your BBB server than tries to download the file. I guess it fails at this point. 

Just tried it from my local installation (where the share url is not reachable from the bbb server), and still can join the meeting, only the presentation is not loaded. So I guess it's a different issue there. Please check your logs, or try to reproduce the request via curl to see what bbb is responding.

**Comment by hokascha** [comment] 2020-06-10 10:29
Got some more information, BBB logs show:

```
2020-06-10T11:59:38.038+02:00 ERROR StackTrace - Full Stack Trace:
java.lang.IllegalStateException: java.io.FileNotFoundException: /usr/share/bbb-web/WEB-INF/lib/unoil-5.4.2.jar (No such file or directory)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntry(AbstractSingleArchiveResourceSet.java:100)
	at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:257)
	at org.apache.catalina.webresources.StandardRoot.getResourcesInternal(StandardRoot.java:327)
	at org.apache.catalina.webresources.CachedResource.validateResources(CachedResource.java:140)
	at org.apache.catalina.webresources.Cache.getResources(Cache.java:129)
	at org.apache.catalina.webresources.StandardRoot.getResources(StandardRoot.java:315)
	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResources(StandardRoot.java:231)
	at org.apache.catalina.loader.WebappClassLoaderBase.findResources(WebappClassLoaderBase.java:958)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResources(WebappClassLoaderBase.java:1053)
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:348)
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
	at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:293)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
	at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
	at groovy.xml.FactorySupport$2.run(FactorySupport.java:58)
	at java.security.AccessController.doPrivileged(Native Method)
	at groovy.xml.FactorySupport.createFactory(FactorySupport.java:35)
	at groovy.xml.FactorySupport.createSaxParserFactory(FactorySupport.java:56)
	at groovy.util.XmlSlurper.<init>(XmlSlurper.java:126)
	at groovy.util.XmlSlurper.<init>(XmlSlurper.java:112)
	at groovy.util.XmlSlurper.<init>(XmlSlurper.java:99)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:242)
	at org.bigbluebutton.web.controllers.ApiController.uploadDocuments(ApiController.groovy:1989)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
	at org.bigbluebutton.web.controllers.ApiController$_closure3.doCall(ApiController.groovy:138)
	at org.bigbluebutton.web.controllers.ApiController$_closure3.doCall(ApiController.groovy)
	at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.bigbluebutton.web.controllers.ApiController.create(ApiController.groovy)
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /usr/share/bbb-web/WEB-INF/lib/unoil-5.4.2.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:196)
	at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:181)
	at org.apache.catalina.webresources.AbstractArchiveResourceSet.openJarFile(AbstractArchiveResourceSet.java:308)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntry(AbstractSingleArchiveResourceSet.java:96)
	... 112 common frames omitted
```

So this might be a BBB Problem, not yours. The share is working and I can download the file via Curl from the BBB server. Anyway, I checked the path for that unoil-5.4.2.jar file that doesn't exist. There is a unoil-4.1.2.jar file there. Any idea what might be wrong?

**Comment by sualko** [comment] 2020-06-10 10:39
Maybe a permission issue? On my servers it looks like this:

```
$ ls -l /usr/share/bbb-web/WEB-INF/lib/unoil-5.4.2.jar
-rw-r--r-- 1 bigbluebutton bigbluebutton 1741056 Feb 21  2019 /usr/share/bbb-web/WEB-INF/lib/unoil-5.4.2.jar
```

According to a internet search it seams that this file is related to libreoffice. So maybe you should try to start a presentation with a pdf file, because in this case libreoffice is not used. This way you can try to isolate the issue.

> So this might be a BBB Problem, not yours.

I think the same. Therefore I close this issue.

**Closed by sualko** 2020-06-10 10:39 UTC

**Comment by hokascha** [comment] 2020-06-10 10:49
I used a pdf file but the jar file is still used. Interesting the file exists on your server but not on mine. Will file that issue with BBB.
