### ISSUE TITLE
404 with disabled shares

### ISSUE THREAD

**Issue by wamagss** [sualko/cloud_bbb#20] opened 2020-04-29 18:41 UTC
Hello,

no matter, how I try to start a BBB-session (from the list of rooms I created or from the ...-menu of a document), the session doesn't start.

From the list of rooms: Pretty error page saying "Datei nicht gefunden" (meaning document not found) and the following error in the apache log:
"GET /index.php/apps/bbb/b/GSrnWGLPq9Rxcbiw HTTP/1.1" 404 14401

From the ...-menu of a suitable document: no reaction, but an error in the console:
Request failed with status code 404
and the following error in the apache log:
"POST /ocs/v2.php/apps/files_sharing/api/v1/shares HTTP/1.1" 404 982

Thanks for any assistance.

Greetings, Matthias

BTW: Is it really necessary to always link a document to a session?

**Comment by joergmschulz** [comment] 2020-04-29 19:57
It might help to read the readme of this app.
- it is not necessary to link a doc to a session - you can also start a session by clicking on the small arrow left to the room name in the BigBlueButton settings.
- do you enforce passwords for sharing in your nextcloud sharing settings? If yes, this may be the reason for the session not appearing.

**Comment by wamagss** [comment] 2020-04-29 20:40
Hello,

Point one: As mentioned, I also tried it that way and it results in "Document not found". This sounds like a related document is needed.

Point two: I certainly read the Troubleshooting and it states, "but a session opens in the general configuration page". This was not the case in my situation, so I thought, this doesn't match my situation.

The start of a session from a document as well as from the BBB-settings does work now.

The problem was, that I disabled sharing by links in general, because our community are teachers and pupils and we don't want to give pupils the opportunity to share documents with someone outside the school because of legal issues.

So maybe this situation could also be mentioned in the Troubleshooting section.

Or even better: Would it be possible to change the app in a way, that no shared links are needed.

Thanks for your help,

Matthias

**Comment by joergmschulz** [comment] 2020-04-29 21:23
the dependency on links will probably be fixed by #1 ???

**Comment by sualko** [comment] 2020-04-30 08:21
> Is it really necessary to always link a document to a session?

No. As you stated you can just join a room if you know the link.

I think you have two issues. First you can't start rooms from the file browser if you don't allow unprotected link shares.

The second issue is more serious: Your 404 when you open a room from the settings page. Usually this means that the token (the last part of the url) is not valid. I have no idea why this happens and how I could debug this without the ability to reproduce this issue. If you like you can try it by your own and `var_dump` the variables in https://github.com/sualko/cloud_bbb/blob/8fe90e0ff86f22bc7338e7d1fdfd9915b616dfb3/lib/Controller/JoinController.php#L57.

**Comment by wamagss** [comment] 2020-04-30 08:40
Hi,

As I wrote in my earlier message, both errors were gone by enabling shared links.

We have a closed community (school) and unfortunately the actual behavior doesn't match our needs. I will create a new issue containing some feature requests and why they are important for us.

Thank you very much for your work with this app and the support you give.

Greetings, Matthias

**Comment by sualko** [comment] 2020-04-30 08:45
I'm not sure why you have to enable link sharing to enter a room via the personal settings page, because I followed the [Nextcloud documentation for public pages](https://docs.nextcloud.com/server/stable/developer_manual/app/publicpage.html). Sounds like a NC issue.

The requirement for link shares to open a room with a presentation is tracked in #1, so I will close this issue.

**Comment by sualko** [comment] 2020-04-30 11:27
> I'm not sure why you have to enable link sharing to enter a room via the personal settings page, because I followed the Nextcloud documentation for public pages. Sounds like a NC issue.

I can reproduce this behavior and therefore I reopen this issue.

**Comment by sualko** [comment] 2020-04-30 11:52
After looking into it, it seams the NC documentation is at least hiding some important points there. So we have to implement our own middleware controller and use that.

**Comment by joergmschulz** [comment] 2020-05-24 17:57
Indeed. The URLs don't work if sharing is disabled. Is this really an issue? The situation is: access to the BBB rooms is only possible when sharing generally is enabled. Is there a usecase 'enable BBB access, but DISable sharing'? Is this usecase so urgent that a separate sharing middleware should be developed?

**Comment by sualko** [comment] 2020-05-24 18:32
> Is this usecase so urgent that a separate sharing middleware should be developed?

As I didn't disable link shares in any of my instances, it's not that urgent for me, but I can imagine that there are some setups which requires to disable link shares. If I have time this is definitely something I want to look into (beside sharing and authentication).

**Comment by joergmschulz** [comment] 2020-05-24 18:58
re: link shares: fully ack!
re: authentication: That's good news as I feel this is the feature missing most. We don't want to replicate the zoom bombing topic.

**Comment by sualko** [comment] 2020-05-24 19:17
> We don't want to replicate the zoom bombing topic.

Our tokens are 16 characters long. With 52 different characters, we get 2,857942575×10²⁷ combinations. If you test 1000 tokens/s and you assume you find a valid one in average after half of all possible keys, you need 4,531238227×10¹⁶ (40 quadrillions) years. Most people assume the earth is 4.5 billion years old. For me that's enough if I didn't do any miscount. :wink:

**Comment by joergmschulz** [comment] 2020-05-24 20:52
Yes, that's true. In the end it doesn't matter whether somebody discloses a link or a link AND a password.

**Closed** 2020-06-04 08:07 UTC
Labels: bug
