### ISSUE TITLE
Compatibility with NextCloud 26

### ISSUE THREAD

**Issue by JeremyCDP** [sualko/cloud_bbb#244] opened 2023-04-06 15:30 UTC
[BigBlueButton Integration ↗](https://apps.nextcloud.com/apps/bbb) is declared as not compatible with Nextcloud 26.

Are there any plans to make it compatible? And if so, is there a visible deadline?

**Comment by znerol** [comment] 2023-04-26 17:54
Release 2.4.0 is declared to be compatible with 25 but not yet with 26. However, it works with 26 as well. Use `php occ app:enable --force bbb` to activate it. With the `--force` flag, `occ` will skip the compatibility check.

Also pushed #249

**Comment by jorgelondo** [comment] 2023-04-26 18:53
Hi @znerol 

I have Next cloud and BBB 2.65 on a separate aws EC2 server each.
I already have Nextcloud integrated with the plugin with bbb, but I have not been able to perform the interface of uploading a file from nextcloud that is shown in the image above.
Can someone help me if there is any guide or step by step? thank you!

![26-next-cloud-2](https://user-images.githubusercontent.com/672505/234674897-b2d1fd25-0d01-4c18-9898-29b9b2a1f0d4.png)

**Comment by strausmann** [comment] 2023-05-30 15:16
When will BBB finally support the NextCloud 26?

**Comment by joergmschulz** [comment] 2023-05-30 15:45
You _can_ enable the app as unsupported.

**Comment by ferfebles** [comment] 2023-06-16 10:33
I will enable and test the app as unsupported in our preproduction environment.

But please, release a new version with support for Nextcloud 26 enabled.

We are not allowed to upgrade with unsupported apps and will have to give up on using this app.

**Comment by strausmann** [comment] 2023-06-16 10:37
I can't quite figure it out either.
Are there any problems with these versions? If there are no problems, then a release is no problem.

**Comment by Grocel** [comment] 2023-06-20 22:01
Sure you can enable experimental or unsupported version. It's nice that it works at all and is probably very useful for public testing and such. But that it is not being official supported yet probably has its good reasons.

Using experimental/unsupported version this is just not acceptable for many professional use cases. I would not recommend to do so. And so shouldn't the actual project collaborator. It is just not good practice.

So if the application is actually good enough to tell the user "just enable the experimental mode" in an issue that asks for a compatibility status, why not just adjust the versions accordingly then? Should be fine then, isn't it? Probably not, because the new version isn't well tested and ready to ship yet.
That's ok, but please don't tell someone to experiment with their installs as a solution then.

Just my 2 cents. I just don't like Schrödingers versioning.

**Comment by ferfebles** [comment] 2023-07-14 11:57
Sadly, the director has decided to move forward leaving bbb integration behind.

**Comment by joergmschulz** [comment] 2023-07-14 12:24
> Sadly, the director has decided to move forward leaving bbb integration behind.

meaning whom? So this integration will vanish?

**Comment by ferfebles** [comment] 2023-07-17 07:53
Only from our site

**Comment by sualko** [comment] 2023-07-27 08:57
Since @znerol added support for every currently maintained NC version, I close this :-)

**Closed by sualko** 2023-07-27 08:57 UTC

**Comment by joergmschulz** [comment] 2023-07-27 10:31
when will this version be released and appear on appstore?

**Comment by sualko** [comment] 2023-07-27 12:02
@joergmschulz I hope later today. I'm currently struggling wie ci and I also want to fix some other bugs before I release a new version.

**Comment by sualko** [comment] 2023-07-27 12:18
@joergmschulz I decided to rather publish a minor release with the NC bumps and the scroll fix and make another release for all other changes. This way you can update faster. I think you all waited way too long.
