### ISSUE TITLE
Not possible to enter moderators

### ISSUE THREAD

**Issue by mariusimi** [sualko/cloud_bbb#56] opened 2020-07-27 10:26 UTC
**Describe the bug**
Hello everyone,
when I create a room and want to make another user a moderator I get him displayed but he does not become a moderator. If I press the name a few times it will work eventually. I haven't made any adjustments to the room settings. This error does not occur permanently. Its occurs with users from the ldap and with local users

**To Reproduce**
1. Go to BBB in your Nextcloud
2. Click on 'edit' at your room
3. Scroll down to 'Moderator'
4. Type in the user ou want to set as a moderator
5. Click on his name
6. See what will happen 

**Expected behavior**
I expect that when I click on a user this user will be set as moderator.

**System (please complete the following information):**
 - Browser with version Safari, Firefox and Chrome
 - App version 0.5.1
 - Nextcloud version 19.0.1
 - BigBlueButton version 2.2.20
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Comment by sualko** [comment] 2020-07-28 13:48
Thanks for your report, but I close it, because it's a duplicate of #49. Currently I'm short of time, so a pr would be appreciated.

**Closed by sualko** 2020-07-28 13:48 UTC
