### ISSUE TITLE
NC18, NC 19 Addidional settings / Zusätzliche Einstellungen: cannot select groups for restriction settings

### ISSUE THREAD

**Issue by joergmschulz** [sualko/cloud_bbb#69] opened 2020-09-01 14:57 UTC
while the groups show up in the dropdown like this: 
<img width="507" alt="grafik" src="https://user-images.githubusercontent.com/6523646/91866678-0eaf8700-ec73-11ea-8944-d77d2d28c64d.png">

I can not select any of these groups.

Furthermore, I cannot remove the All users entry from the first line.

The sharing sessions on this test system are quite open:

<img width="544" alt="grafik" src="https://user-images.githubusercontent.com/6523646/91866881-48808d80-ec73-11ea-9e87-4c3226677467.png">

Maybe something failed with the db migration? Am using postgres

This time, nextcloud log has more error info:
**Nextcloud log:**

`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE "oc_bbb_restrictions" SET "allow_recording" = ? WHERE "id" = ?' with params [false, 1]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type boolean: ""`

```
[index] Error: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE "oc_bbb_restrictions" SET "allow_recording" = ? WHERE "id" = ?' with params [false, 1]:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type boolean: "" at <<closure>>

 0. /www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException("An exception oc ... "", Doctrine\DBAL\Dr ... ]})
 1. /www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 145
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOPgSql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... "")
 2. /www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1063
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOPgSql\Driver {}, Doctrine\DBAL\Dr ... ]}, "UPDATE \"oc_bbb ... ?", {1: "*** sensiti ... "})
 3. /www/nextcloud/lib/private/DB/Connection.php line 214
    Doctrine\DBAL\Connection->executeUpdate("UPDATE \"oc_bbb ... ?", ["*** sensitive  ... "], [2,"*** sensitiv ... "])
 4. /www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php line 203
    OC\DB\Connection->executeUpdate("UPDATE \"oc_bbb ... 2", {dcValue1: "***  ... "}, {dcValue1: 2,dcV ... "})
 5. /www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 216
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /www/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 203
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /www/nextcloud/custom-apps/bbb/lib/Service/RestrictionService.php line 95
    OCP\AppFramework\Db\QBMapper->update("*** sensitive parameters replaced ***")
 8. /www/nextcloud/custom-apps/bbb/lib/Controller/RestrictionController.php line 96
    OCA\BigBlueButton\Service\RestrictionService->update("*** sensitive parameters replaced ***")
 9. /www/nextcloud/custom-apps/bbb/lib/Controller/Errors.php line 16
    OCA\BigBlueButton\Controller\RestrictionController->OCA\BigBlueButton\Controller\{closure}("*** sensitive parameters replaced ***")
10. /www/nextcloud/custom-apps/bbb/lib/Controller/RestrictionController.php line 103
    OCA\BigBlueButton\Controller\RestrictionController->handleNotFound(Closure {})
11. /www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\BigBlueButton\Controller\RestrictionController->update("*** sensitive parameters replaced ***")
12. /www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\BigBlueButto ... {}, "update")
13. /www/nextcloud/lib/private/AppFramework/App.php line 137
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\BigBlueButto ... {}, "update")
14. /www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\BigBlueBut ... r", "update", OC\AppFramework\ ... {}, {id: "1",_route: ... "})
15. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({id: "1",_route: ... "})
16. /www/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {id: "1",_route: ... "})
17. /www/nextcloud/lib/base.php line 1012
    OC\Route\Router->match("/apps/bbb/restrictions/1")
18. /www/nextcloud/index.php line 37
    OC::handleRequest()

PUT /index.phprestrictions/1
from 192.168.176.12 by joerg.schulz at 2020-09-01T13:19:01+00:00```

**Comment by sualko** [comment] 2020-09-02 08:13
> I can not select any of these groups.

I guess this is related to your posted log entry, but it would help if you could post all xhr requests after clicking on an entry. Meanwhile I will add some more integration tests to see if I can reproduce this.

> Furthermore, I cannot remove the All users entry from the first line.

That's intended, because it's the default value. If you like to disable room creation by default, set -1 for the room number.

**Comment by joergmschulz** [comment] 2020-09-02 08:38
Hmmm, nothing spectacular visible in the browser console (not that I'm an expert developer). 
Would you say that -1 deactivates the room creation? I felt it is 0, and -1 stands for 'unlimited'?

**Comment by sualko** [comment] 2020-09-02 08:40
> Hmmm, nothing spectacular visible in the browser console 

Can you look at the network tab. There should be a post request.

> Would you say that -1 deactivates the room creation? I felt it is 0, and -1 stands for 'unlimited'?

Sorry. You are right. 0 deactivates room creation, -1 means unlimited.

**Comment by sualko** [comment] 2020-09-02 08:44
Travis is now failing for postgres db and therefore I can start working on a solution, but I'm still wondering why this is not handled by nc...

**Comment by sualko** [comment] 2020-09-02 09:01
fixed via a24f8a1f9635f274d80914cf472568f27fb4543a

**Comment by joergmschulz** [comment] 2020-09-02 13:22
believe it or not - using Edge, it works. Firefox, Chrome, Safari have issues. Or did I miss some browser reset settings? I claim to have reset the browser caches.Awfully sorry I can't find anything meaningful in the browser consoles. 
I can click on the greyed suggestions, but nothing happens. Using Edge, they're selected. Don't have this issue with other group selection boxes.

**Comment by sualko** [comment] 2020-09-04 09:00
I guess your latest problems are not related to the original cause of this issue and sadly I can't reproduce it. It works in Chrome, Vivaldi and Firefox at least on Linux. Can you look at the network tab in your dev console to see if there are any requests?

**Comment by joergmschulz** [comment] 2020-09-04 12:40
indeed. The difference is: on the working Edge, there is activity in the network tab when I click on the dropdown; on browsers where it isn't working, there is none. Adding firefox on windows to the not-working browsers.

**Comment by sualko** [comment] 2020-09-04 15:14
For some reason the click event is not handled correctly. To discuss this in more detail, I opened a new issue #73. It would be nice if you could describe the process there in more detail. What happens if you click on an item? Is the list closing? Is it always the same behavior independent on the region where you click? Do you have the same issue in the room configuration dialog?

**Closed by sualko** 2020-09-04 15:14 UTC
Labels: bug
