### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by comlocke** [sualko/cloud_bbb#168] opened 2021-07-11 20:24 UTC
**Describe the bug**
Column "oc_bbb_rooms"."record" is type Bool and also NotNull, so it can not store "false".

**To Reproduce**
1. Go to 'Nextcloud-Apps -> BigBluButton Integration'
2. Click on 'activate'
4. See error "Column "oc_bbb_rooms"."record" is type Bool and also NotNull, so it can not store "false"."

**Expected behavior**
I think there was further a dataprint into the maria_db database.

**Screenshots**
![image](https://user-images.githubusercontent.com/87281371/125208785-e8944380-e294-11eb-9ceb-9740247a3406.png)

**System (please complete the following information):**
 - Browser with version chrome Version 91.0.4472.114 (Offizieller Build) (x86_64)]
 - App version unknown, it was not installed
 - Nextcloud version 22.0.0
 - BigBlueButton version [e.g. 2.3.0]
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:**

```
"reqId":"ryjiGJO2PhMVRvFtBVLv","level":2,"time":"2021-07-07T16:54:37+00:00","remoteAddr":"46.223.3.53","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15","version":""}
{"reqId":"ryjiGJO2PhMVRvFtBVLv","level":2,"time":"2021-07-07T16:54:37+00:00","remoteAddr":"46.223.3.53","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15","version":""}
{"reqId":"dzbrwfWyO7HTUVXAkvH5","level":2,"time":"2021-07-07T16:57:18+00:00","remoteAddr":"46.223.3.53","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15","version":""}
{"reqId":"dzbrwfWyO7HTUVXAkvH5","level":2,"time":"2021-07-07T16:57:18+00:00","remoteAddr":"46.223.3.53","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15","version":""}
{"reqId":"dzbrwfWyO7HTUVXAkvH5","level":3,"time":"2021-07-07T16:57:18+00:00","remoteAddr":"46.223.3.53","user":"--","app":"PHP","method":"POST","url":"/index.php","message":"mkdir(): No such file or directory at /var/www/nextcloud/lib/private/Setup.php#305","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15","version":"","exception":{"Exception":"Error","Message":"mkdir(): No such file or directory at /var/www/nextcloud/lib/private/Setup.php#305","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Setup.php","line":305,"function":"mkdir"},{"file":"/var/www/nextcloud/core/Controller/SetupController.php","line":74,"function":"install","class":"OC\\Setup","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/base.php","line":939,"function":"run","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"YXLF1kZ0rK02qZPhPsf5","level":2,"time":"2021-07-07T16:59:54+00:00","remoteAddr":"46.223.3.53","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15","version":""}
{"reqId":"YXLF1kZ0rK02qZPhPsf5","level":2,"time":"2021-07-07T16:59:54+00:00","remoteAddr":"46.223.3.53","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15","version":""}
```

**Comment by sualko** [comment] 2021-07-12 06:37
duplicate of #164

**Closed by sualko** 2021-07-12 06:37 UTC
