### ISSUE TITLE
Public room URL does not work when you are signed into the Nextcloud and are not in a group allowing BBB

### ISSUE THREAD

**Issue by jacotec** [sualko/cloud_bbb#125] opened 2021-02-13 14:39 UTC
**Describe the bug**
When I receive the public BBB room URL from another user and I'm signed into my own account in Nextcloud, I'm not seeing the "Enter your Name" page and can't proceed to the conference in case the use of BBB is restricted to groups and I'm not a member of the group.
Instead, the room URL just opens my own "files" page in Nextcloud.

The only way to participate in the conference in this case would be logging out from Nextcloud.

**To Reproduce**
1. Create a room as user A and copy the public URL of the room
2. The BBB use is restricted to the group "BBBUser"
2. Logout or open another, different browser
3. Login to the same Nextcloud as User B. User B must not be a member of "BBBUser"
4. Paste the URL into your browser
5. You'll just being redirected to your files page in nextcloud.

**Expected behavior**
You should either see the "Enter your Name" page, or being directly redirected to the room / waiting page as Nextcloud already knows your name (as you are logged in).
Restricting the use of BBB to a group should remove the BBB icon/item and the user can't create and use own rooms. Nevertheless, he should be able to join a conference which is created by another user who has the rights to use the BBB.

**System (please complete the following information):**
 - Browser with version [e.g. chrome, safari] Any (Chrome, Safari, Firefox)
 - App version [e.g. 0.1.0] 1.2.0
 - Nextcloud version [e.g. 18.0.1] 20.0.7
 - BigBlueButton version [e.g. 2.2.9] 2.2.31
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Comment by sualko** [comment] 2021-02-13 18:24
Duplicate of https://github.com/sualko/cloud_bbb/issues/53

Don't restrict the app to groups, instead use the internal restrictions.

**Closed by sualko** 2021-02-13 18:24 UTC
Labels: duplicate

**Comment by jacotec** [comment] 2021-02-13 18:45
Sorry, I did not see this. You're right!
