### ISSUE TITLE
After installation of 1.0.0, the config menu is no longer visible in NC 18.0.8

### ISSUE THREAD

**Issue by joergmschulz** [sualko/cloud_bbb#68] opened 2020-09-01 10:51 UTC
**Describe the bug**
Access to existing room works while the config screen no longer appears in the user's properties

**To Reproduce**
1. Go to user's properties
2. BBB config not visible

**Expected behavior**
config should be visible 

**Screenshots**
<img width="236" alt="grafik" src="https://user-images.githubusercontent.com/6523646/91840785-8d93c800-ec51-11ea-8abd-86399e5aeb65.png">

**System (please complete the following information):**
 - Browser with version Firefox, Chrome
 - App version [1.0]
 - Nextcloud version 18.0.8

 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:** 
nothing here

**Javascript log:**

```
{"id":1,"groupId":"","maxRooms":-1,"roomTypes":[],"maxParticipants":-1,"allowRecording":false}
```
returns an error 500

**Additional context**

> php occ app:check-code bbb
Analysing /var/www/nc/apps/bbb/lib/Controller/JoinController.php
 2 errors
    line   90: == - is discouraged
    line   97: == - is discouraged
App is not compliant

**Comment by sualko** [comment] 2020-09-01 12:21
Sorry for encountering issues with the latest release. I have trouble to reproduce your issue, because it's working on a test installation with NC 19 and a productive instance with NC 18. Maybe you can answer the following questions:

- On which page do you get the 500 error? 
- Where is the js log coming from? 
- Do you see the admin options?
- What happens if you enable the new "app icon" in app navigation?
- Can you access the settings page by visiting `/index.php/settings/user/bbb`?

Thanks for submitting those two findings from `app:check-code` they will be fixed in the next release, but this is unrelated to this issue.

**Comment by sualko** [comment] 2020-09-01 12:53
Can you try to add the following to the `<section>` element in `appinfo/info.xml`. This should not be needed, but maybe it works.

```
<personal-section>OCA\BigBlueButton\Settings\Section</personal-section>
```

**Comment by joergmschulz** [comment] 2020-09-01 13:01
ha! the <personal-section>OCA\BigBlueButton\Settings\Section</personal-section> has helped in 19 as well as in nextcloud 18.

Still, I can't select groups in the general settings page. Can this be related to my use of LDAP as provider? Will examine and eventually create a new issue.

**Comment by sualko** [comment] 2020-09-01 13:11
> ha! the OCA\BigBlueButton\Settings\Section has helped in 19 as well as in nextcloud 18.

Good news, but this should not be required. I was able to reproduce your issue on another production instance, but I'm not sure what's going on here.

> Still, I can't select groups in the general settings page. Can this be related to my use of LDAP as provider? Will examine and eventually create a new issue.

I don't know what you mean with "general settings" page, but it should not be related to your LDAP config. It's using the share api, so if you have restricted sharing it could maybe not work. If you open a new issue, please include if it worked with the version before.

**Comment by nick-knatterton** [comment] 2020-09-01 19:04
I've got the same error with NC 18.0.6
After updating the BBB-App version 0.5.1 to 1.0.0 the entry in the personal section is missing; therefore no (still existing) rooms are offered for configuration. 
The administration section has the menu entry für additional settings. If I set the check mark to bring the manager to the app menu nothing happens. Also an deactivation followed by an activation of the app has no effect. So I've no chance to reach my (existing) bbb-rooms.

**Comment by joergmschulz** [comment] 2020-09-01 19:10
see above. First aid is to add

`<personal-section>OCA\BigBlueButton\Settings\Section</personal-section>
`
in the <settings> section of info.xml

**Comment by nick-knatterton** [comment] 2020-09-01 19:58
Thanks, it works after I put the line into the <settings> element.

**Closed** 2020-09-02 08:08 UTC
Labels: bug

**Comment by sualko** [comment] 2020-09-02 08:10
I can reproduce this issue only on one of 4 Nextcloud instances. Therefore I assume it's interfering with another app or it's a timing issue. Because I don't have endless time to debug this, I decided to integrate the proposed fix. It also has no downsides.

> If I set the check mark to bring the manager to the app menu nothing happens. 

If you still see no changes after you reload the page, it would be nice if you could open an issue.
