### ISSUE TITLE
Not possible to enter moderators and users  with room setting "internal restricted"

### ISSUE THREAD

**Issue by lars-becker** [sualko/cloud_bbb#49] opened 2020-06-18 16:35 UTC
When selecting "internal limited" it's not possible to select users with access and/oder moderators. The drop down list is displayed and you can search for users or groups but you can't select them.

**To Reproduce**
1. Go to BBB settings. Set up a room and go to the room settings.
2. Configure access mode "internal restricted" / "intern eingeschränkt"  
3. Try to select the users you want to select.

Tested with Nextcloud 19 und cloud_bbb 0.5.

**System (please complete the following information):**
 - Firefox 77.0.1 64bit for Archlinux
 - App version 0.5
 - Nextcloud version 19.0.0
 - BigBlueButton version 2.2.17
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Javascript log:**

1. PUT https://euhh.***.org/index.php/apps/bbb/rooms/1 [HTTP/1.1 200 OK 273ms]

```
{"id":1,"uid":"q25Q4bnxSKrMoZZo","userId":"lars.becker","name":"Vorstand","welcome":"Willkommen im Vorstands-Raum.","maxParticipants":25,"record":false,"access":"internal_restricted","password":null,"everyoneIsModerator":false}
```

2. GET https://euhh.***.org/ocs/v1.php/apps/files_sharing/api/v1/sharees_recommended?itemType=room&format=json
[HTTP/1.1 200 OK 450ms]

Response:
```
{"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},"data":{"exact":{"users":[{"count":1,"label":"* *","value":{"shareType":0,"shareWith":"*.*"}}],"groups":[],"remotes":[],"remote_groups":[],"emails":[{"count":2,"label":"mail@*","value":{"shareType":4,"shareWith":"mail@*"}},{"count":1,"label":"*@*.*","value":{"shareType":4,"shareWith":"*@*"}},{"count":1,"label":"*@*","value":{"shareType":4,"shareWith":"*@*"}},{"count":1,"label":"*@web.de","value":{"shareType":4,"shareWith":"*l@web.de"}}]},"users":[],"groups":[],"remotes":[],"remote_groups":[],"emails":[]}}}
```

(In this list it seems that these are mostly remote users from a cloud with which adressbooks are shared via federation.)

3.  GET https://euhh.*.org/ocs/v1.php/apps/files_sharing/api/v1/sharees?search=&shareType[]=0&shareType[]=1&itemType=room&format=json&lookup=false
[HTTP/1.1 200 OK 266ms]

result

```
{"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},"data":{"exact":{"users":[{"label":"* *","value":{"shareType":0,"shareWith":"*.*"}},{"label":"lars","value":{"shareType":0,"shareWith":"demo"}}],"groups":[],"remotes":[],"remote_groups":[],"emails":[],"circles":[],"rooms":[]},"users":[{"label":"* *","value":{"shareType":0,"shareWith":"*.*"}},{"label":"* *","value":{"shareType":0,"shareWith":"*.*"}},{"label":"Cloud Administrator","value":{"shareType":0,"shareWith":"euhh"}},{"label":"* *","value":{"shareType":0,"shareWith":"daniel.kosak"}},{"label":"demo1","value":{"shareType":0,"shareWith":"demo1"}},{"label":"* *","value":{"shareType":0,"shareWith":"*.*@*"}},{"label":"* *","value":{"shareType":0,"shareWith":"*.*"}},{"label":"* * *","value":{"shareType":0,"shareWith":"*.*.*"}},{"label":"* *","value":{"shareType":0,"shareWith":"*.*"}},{"label":"* *","value":{"shareType":0,"shareWith":"*.*"}},{"label":"Landesgesch\u00e4ftsstelle EUHH","value":{"shareType":0,"shareWith":"lgst"}},{"label":"Lars @ Gastkonto (Testbenutzer)","value":{"shareType":0,"shareWith":"lars@*"}},{"label":"* *","value":{"shareType":0,"shareWith":"*.*"}},

and so on [...]

{"shareType":1,"shareWith":"Vorstand"}},{"label":"admin","value":{"shareType":1,"shareWith":"admin"}},{"label":"app_mail","value":{"shareType":1,"shareWith":"app_mail"}},{"label":"Everyone","value":{"shareType":1,"shareWith":"everyone"}}],"remotes":[],"remote_groups":[],"emails":[],"lookup":[],"circles":[],"rooms":[],"lookupEnabled":false}}}
```

What is strange is, that the behaviour is not entirely deterministic. Sometimes when I scroll to the list I can select entries; but more often I can not. It seems that the browser isn't always sending the request. I have some add-ons like uBlock and Noscript, but disabled them. Trying the same operation on Google Chrome without any add-ons produces the same behaviour. What's strange also, is that I can select some users, remove them and can't select them again.  I could never select the two first entries, but I haven't found other stable patterns yet since sometimes I could select some users, removed them I tried to select them again, which didn't work the 2nd time…

**Comment by joergmschulz** [comment] 2020-06-18 19:06
even worse here  - as the user lookup is restricted, no dropdown shows up at all

**Comment by joergmschulz** [comment] 2020-06-18 19:54
here, this might have something to do with LDAP integration. As long as the room configuration window is open, the nextcloud log is flooded with: 

```
Info | no app in context | Deprecated event type for OCA\User_LDAP\User\User::postLDAPBackendAdded: null
-- | -- | --
```

**Comment by sualko** [comment] 2020-06-19 06:21
@lars-becker thanks for your bug report. It would be great if you could fill the issue template, because this information is important to close an issue asap. As you may can imagine, it's working fine for me, so it would be helpful to see if there are any javascript log entries or which browser you are using.

@joergmschulz please open an issue for that, because it's unrelated.

**Comment by joergmschulz** [comment] 2020-06-19 08:11
true, deleted that post, unrelated to bbb as far as I see. Lars-Becker-bug is reproducible for NC18&19, but as far as I can see, nothing useable turns up in the logs nor in the browser console. Still looking...

**Comment by lars-becker** [comment] 2020-06-19 09:34
@sualko Sorry, I haven't much experience with front end. I added some information to the report, but to me it doesn't seem that helpful. If you have something more specific in mind please let me know and I try to obtain this information.

**Comment by sualko** [comment] 2020-06-21 10:20
> is not entirely deterministic

That's the worst case. I can try to change the drop down behavior and hope that it will fix your issue. Currently it's closing the dropdown 100ms after the input has no focus, because the blur event is handled before the click event. Maybe we need something better here.

**Closed** 2020-08-25 13:21 UTC
